# その他

## パッケージ内で日本語を使う

Rのパッケージに非ASCII文字を含めることは推奨されない。だが可能だ。

具体的には、`DESCRIPTION`に`Encoding`を指定しつつ、

1. `\uXXXX`のエスケープを使う
2. データに含める
3. メッセージ翻訳の仕組みを使う

のいずれかの手を使う。

### `DESCRIPTION`

`Encoding`フィールドに`UTF-8`を指定する。これはおそらくいずれの手を使うにしても必要なはず。

```
Encoding: UTF-8
```

あと、[Writing R Extensions](http://www.hep.by/gnu/r-patched/r-exts/R-exts_35.html)によると、厳密には、

```
Depends:
  R (>= 2.10)
```

も指定しないといけないらしい。

### `\uXXXX`のエスケープを使う

これがR Packagesが推奨している方法^[http://r-pkgs.had.co.nz/r.html#r-cran]。
`stringi::stri_escape_unicode()`を使うとエスケープされた文字列を知ることができる。たとえば、「あ」という文字列を使いたいなら、

```{r stringi}
cat(stringi::stri_escape_unicode("あ"))
```

ということで、`"あ"`の代わりに`"\u3042"`と書けばいい。UTF-8になっているので、デフォルトの文字コードと合わせたいなら`enc2native()`する必要がある点に注意。

### データに含める

UTF-8にした文字列をデータとしてパッケージに含める、という手もある。
ただし、これは最近、CRAN checkの結果に

```
Result: NOTE
     Note: found 52458 marked UTF-8 strings 
```

という表示が出るのが気になる。いずれ使えなくなる？

### メッセージの翻訳の仕組みを使う

あまり使われているのを見かけないが、Rにはメッセージの翻訳の仕組みがある^[[DYMパッケージ](https://github.com/kos59125/DYM)はこの仕組みを使っている]。
日本語を含めたい理由がメッセージを表示させるためであれば、これを使う手もある。具体的には、以下の流れになる。

1. `tools::update_pkg_po(".")`を実行する。ソースコード中の`stop()`、`warning()`、`message()`のメッセージを読み取って`po/R-パッケージ名.pot`というメッセージ翻訳のテンプレートができる。
2. テンプレートファイルをコピーして`po/R-ja.po`（または`po/ja.po`）というファイルをつくる。
3. `inst`下にインストールする^[http://www.hep.by/gnu/r-patched/r-exts/R-exts_41.html] 。Windowsの場合あらかじめ`gettext`のインストールが必要^[ https://www.stats.ox.ac.uk/pub/Rtools/goodies/gettext-tools.zip から入手できる] 。
```sh
mkdir -p inst/po/ja/LC_MESSAGES
msgfmt -c --statistics -o inst/po/ll/LC_MESSAGES/R-パッケージ名.mo po/R-ja.po
```

なお、翻訳の仕組みを使う場合、`stop()`等には`domain = "R-パッケージ名"`を指定しておいた方が無難。

## dynamic registeration of S3 method

## Rcpp

## C

「Advanced R」のCの関数についての章はまだ第二版にはないのでひとまず第一版を参照。

* [R's C interface](https://adv-r.had.co.nz/C-interface.html)

### ヘッダファイル

Cの関数を使えるようにするには以下のヘッダをincludeする。

```c
#include <R.h>
#include <Rinternals.h>
```

#### `R_NO_REMAP`

[R Internals（Hadley版の方）](https://github.com/hadley/r-internals/blob/cca966e7eaaf7758b13901f8a90b67acc0f789e2/README.md#r-internals)によると、

> we recommend that you use `R_NO_REMAP` so all API functions have the prefix `R_` or `Rf_`

とあるが、これをdefineすると`allocVector()`や`asReal()`のような関数も動かなくなってしまうので注意。

#### `USE_RINTERNALS`

[R Internals（公式）](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#The-write-barrier)によれば、

> The only way to obtain direct access to the internals of the `SEXPREC`s is to define `'USE_RINTERNALS'` before including header file `Rinternals.h`,

とある。rlangとかdplyrでも使ってないので、たぶん必要になることはなさそう。

### 関数の登録

Rcppと違って、Cの関数は自分で登録しないといけない。具体的には、`init.c`みたいなやつを作って以下を書く。
例えば`SEXP foo(SEXP, SEXP);`というCの関数を別ファイルで定義しているとすると、以下のようになる。

なお、`R_registerRoutines()`あたりについては、R 3.4以降のことなのでAdvanced R第1版にも載っていない。
[Registering Routines with Rcpp](https://ironholds.org/registering-routines/)あたりを参考のこと（うまく説明できない）。

```c
#include "./foo.h"

// TODO: これはincludeしなくてもコンパイルできたので要らないのかも
#include <R_ext/Rdynload.h>

// 同名・同じシグネチャの関数をexternで定義する
extern SEXP foo(SEXP, SEXP);

// R_registerRoutines()で関数を登録するためのエントリ
static const R_CallMethodDef CallEntries[] = {
  {"foo", (DL_FUNC) &foo, 2},  // 最後の数字は引数の数
  {NULL, NULL, 0}              // 最後にこのNULLのエントリを入れるのがお作法っぽい
};

// 関数名はR_init_<DLL名>にする。<DLL名>は@useDynLibに指定するもの
void R_init_foo(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
```

あと、Rの側では、以下のように`@useDynLib`を指定しておく必要がある。

```r
#' @useDynLib foo, .registration = TRUE
```


## ALTREP

### C++でALTREPを使う

`<R_ext/Altrep.h>`はR 3.5.xの時点ではC++に対応していない。r-develでの指摘^[https://stat.ethz.ch/pipermail/r-devel/2018-October/076952.html] を受けて修正が入った^[https://github.com/wch/r-source/commit/14365e4419d08ced8e987d5d49b26843d1324297] のでR 3.6.0以降で使うには問題ない。

Romain François氏によれば、以下のようにすればいいらしい^[https://stat.ethz.ch/pipermail/r-devel/2018-October/076963.html]。

```cpp
#if R_VERSION < R_Version(3, 6, 0)
  #define class klass
  extern "C" {
    #include <R_ext/Altrep.h>
  }
  #undef class
#else
  #include <R_ext/Altrep.h>
#endif
```

より長いバージョンは以下のレポジトリを参照。

* https://github.com/romainfrancois/altrepisode/blob/96af0548a9ecc08701d119ea427e16940a82882b/src/altrepisode.h


## Apache Arrow

